image: python:3.14

stages:
  - pruebas
  - analisis

pruebas:
  stage: pruebas

  tags:
    - control-misiones

  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt

  script:
    - python -m pytest

analisis-sonarqube:
  stage: analisis

  tags:
    - control-misiones

  image:
    name: sonarsource/sonar-scanner-cli:11
    entrypoint: [""]

  script:
    - sonar-scanner -Dsonar.host.url="${SONAR_HOST_URL}"