services:
  postgres:
    image: postgres:17
    container_name: control-misiones-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: control_misiones
      POSTGRES_USER: usuario_misiones
      POSTGRES_PASSWORD: contraseña_misiones
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: